"""Navigation logic based on detected oil regions.

The navigator consumes high‑level summaries of detection results and
decides steering commands.  It does not perform any image
processing itself.  Instead, it examines the size and position of
detected regions to choose between commands such as ``left``,
``right``, ``forward`` and ``stop``.  Thresholds and output
commands are configurable via the :class:`NavigatorConfig` dataclass.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List

from .detector import DetectionResult, OilRegion


@dataclass
class DetectionSummary:
    """Summary of detected oil regions used by the navigator."""

    num_regions: int = 0
    max_area: float = 0.0
    centroid_x: float = 0.0
    centroid_y: float = 0.0


@dataclass
class NavigatorConfig:
    """Configuration parameters for the navigator."""

    frame_width: int
    left_threshold: float = 0.4
    right_threshold: float = 0.6
    left_command: str = "left"
    right_command: str = "right"
    forward_command: str = "forward"
    stop_command: str = "stop"
    area_threshold: float = 5000.0


class Navigator:
    """Decide navigation commands based on oil detection summaries."""

    def __init__(self, config: NavigatorConfig) -> None:
        self.config = config

    def summarise(self, detection_result: DetectionResult) -> DetectionSummary:
        """Create a summary of the detection result for navigation.

        The summary focuses on the largest region by area and records the
        total number of regions.  If no regions are found the summary
        contains zeroes.

        Parameters
        ----------
        detection_result : DetectionResult
            Output from the detector containing regions and the frame.

        Returns
        -------
        DetectionSummary
            Summarised information about the detected regions.
        """
        regions: List[OilRegion] = detection_result.regions
        if not regions:
            return DetectionSummary()
        # Find region with the maximum area
        largest = max(regions, key=lambda r: r.area)
        summary = DetectionSummary(
            num_regions=len(regions),
            max_area=largest.area,
            centroid_x=float(largest.centroid[0]),
            centroid_y=float(largest.centroid[1]),
        )
        return summary

    def decide(self, summary: DetectionSummary) -> str:
        """Determine the navigation command based on a summary.

        Rules
        -----
        1. If no regions are detected or the largest region is below
           ``area_threshold``, return ``stop_command``.
        2. Compute the normalised x‑coordinate of the largest region's
           centroid (between 0 and 1).  If it lies below
           ``left_threshold`` return ``left_command``.  If it lies above
           ``right_threshold`` return ``right_command``.  Otherwise
           return ``forward_command``.

        Parameters
        ----------
        summary : DetectionSummary
            Summary generated by :meth:`summarise`.

        Returns
        -------
        str
            One of the configured commands: ``left``, ``right``,
            ``forward`` or ``stop``.
        """
        # Rule 1: stop if nothing significant is detected
        if summary.num_regions == 0 or summary.max_area < self.config.area_threshold:
            return self.config.stop_command
        # Derive the normalised x coordinate of the centroid
        if self.config.frame_width <= 0:
            # Fallback: treat the centroid as centred
            x_norm = 0.5
        else:
            x_norm = summary.centroid_x / float(self.config.frame_width)
        # Decide on direction
        if x_norm < self.config.left_threshold:
            return self.config.left_command
        elif x_norm > self.config.right_threshold:
            return self.config.right_command
        else:
            return self.config.forward_command